### ISSUE TITLE
Guide:  Device Workflow > Show Workflow step

### ISSUE THREAD

**Issue by dickkluis** [LagoVista/docs#11]
The help box does not display and Chrome shows the following error:

![6554769C-FE7E-41C4-AC59-9BA33BE7F03E](https://user-images.githubusercontent.com/43004783/71598669-c7865a80-2b15-11ea-97ed-d7a037c2acea.png)

**Comment by bytemaster-0xff** [comment]
fixed in localdev

**Comment by dickkluis** [comment]
Fixed
