### ISSUE TITLE
Vertical Scrolling seems disabled

### ISSUE THREAD

**Issue by dickkluis** [LagoVista/docs#16]
Tested Chrome and Safari.  Both don't scroll at all anymore one you open a tutorial (guide)

Firefox seems to still scroll.

**Comment by dickkluis** [comment]
Note:  There are some situations were scrolling seems to work but I cannot recreate how I got that.

**Comment by bytemaster-0xff** [comment]
is this still an issue?  I checked 4/5 views and it seems like I could scroll....

**Comment by dickkluis** [comment]
It seems to work for me too now.
