### ISSUE TITLE
ChildList Identifier help needed:

### ISSUE THREAD

**Issue by dickkluis** [LagoVista/docs#17]
On Planners:

- Device ID Parsers
- Device Type ID Parsers

On Solutions:

- Listeners
- Device Configurations
- Settings

Will put others into additional comments when I find them

**Comment by bytemaster-0xff** [comment]
Will let you know when I publish but for planner:
deviceid-parserslist
and 
messageid-parserslist

**Comment by bytemaster-0xff** [comment]
For solution
settings-list
deviceconfig-list
listeners-list

**Comment by bytemaster-0xff** [comment]
did not have id's I added the id's I built guides for parser, they worked.  Solution was straight forward but didn't tests

**Comment by dickkluis** [comment]
> Will let you know when I publish but for planner:
> deviceid-parserslist
> and
> messageid-parserslist

The above are working.   Starting on the Solution stuff now

**Comment by dickkluis** [comment]
Tried the listeners list.   Getting errors.   It looks like the childlist is being recognized but the row-key is not found.   As far as I can tell I entered the row key the right way.

First I thought that the childlist name was not right and it needed the uppercase L but that gave a completely different error when I tried that.

Here is the error.

![F187F5F7-43F7-4F56-AE79-65BB2D47B78E](https://user-images.githubusercontent.com/43004783/71722411-aadc7200-2df6-11ea-8090-8374214dc12c.png)

**Comment by dickkluis** [comment]
The same type of error happens for the deviceconfig-list

**Comment by dickkluis** [comment]
I tried something different for the settings-list since there is no entry yet.   Tried using the + Add option and got this error.

![0BD73E1C-3238-46E5-96D0-66144AB5EFE9](https://user-images.githubusercontent.com/43004783/71722917-bf216e80-2df8-11ea-9709-59f14ba64f58.png)

**Comment by bytemaster-0xff** [comment]
I think we are good on all of these now, correct?  If so can you close it?

**Comment by dickkluis** [comment]
Fixed
