### ISSUE TITLE
Messaging/Parsing Verifiers Header Displays improperly

### ISSUE THREAD

**Issue by klworkman** [LagoVista/docs#6]
I have checked this header against other pages and can't find a reason for it to be behaving differently.  The full header displays in the body of the page, without formatting.

**Comment by klworkman** [comment]
This happened when I had only one space between the "status:" field and the status.  I went back and fixed it.

**Comment by bytemaster-0xff** [comment]
Yeah – the markdown stuff is a bit “tricky” but once you get the hang of it, it makes creating generic formats you can apply a style to later really easy.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
