### ISSUE TITLE
Mobile Apps - Second sentence unclear 

### ISSUE THREAD

**Issue by klworkman** [LagoVista/docs#7]
Mobile Apps

NuvIoT is a complete, end-to-end system. It allows you to capture and process data from sensors and devices. After all, without devices and sensors, you cannot have IoT.

**Although the is created** by your devices and sensors, the real value comes in when that data is put to use. In addition to providing online tools to manage and report on incoming data, we offer two paths for Mobile Apps.

**Comment by bytemaster-0xff** [comment]
@klworkman ah yes, some of that content I pushed in there pretty quick :) 

Although the data is created by your devices and sensors, the real value comes when that data is put to use. In addition to providing online tools to manage and report on incoming data, we offer two paths for Mobile Apps.

**Comment by bytemaster-0xff** [comment]
If I don't speak to the "Mobile Apps" in the next section...just set the status to "inprocess" and I'll cleanup later

**Comment by klworkman** [comment]
Thanks, I think the rest is fine but will double check.

**Comment by klworkman** [comment]
Crap, I should have been able to figure that one out.  Sorry.

**Comment by bytemaster-0xff** [comment]
my gosh, not an issue!

**Comment by bytemaster-0xff** [comment]
If you have everything you need here, just go ahead and close this item...I'll cleanup up the other items later today.
